import { StyleSheet, Text } from 'react-native';

export default function LongText() {
    return (
        <Text>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Mauris dictum facilisis augue. Nunc tincidunt ante vitae massa. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Etiam commodo dui eget wisi. Duis pulvinar. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. In rutrum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Quisque porta. In sem justo, commodo ut, suscipit at, pharetra vitae, orci. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Nulla est.

Vivamus ac leo pretium faucibus. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Nulla non arcu lacinia neque faucibus fringilla. Nunc dapibus tortor vel mi dapibus sollicitudin. Etiam commodo dui eget wisi. Phasellus et lorem id felis nonummy placerat. Maecenas libero. Fusce suscipit libero eget elit. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Cras elementum. Sed convallis magna eu sem. Quisque porta. Mauris elementum mauris vitae tortor. Mauris metus. Aenean placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Nam sed tellus id magna elementum tincidunt.

Pellentesque arcu. Aenean placerat. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Vivamus porttitor turpis ac leo. Phasellus rhoncus. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Nulla est. Vivamus porttitor turpis ac leo. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Vivamus porttitor turpis ac leo. Aliquam erat volutpat. Maecenas lorem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Nulla est. Aliquam ornare wisi eu metus. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Integer pellentesque quam vel velit.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Phasellus faucibus molestie nisl. Proin in tellus sit amet nibh dignissim sagittis. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Aenean placerat. Nam sed tellus id magna elementum tincidunt. Nullam rhoncus aliquam metus. Duis pulvinar. Phasellus et lorem id felis nonummy placerat. Maecenas lorem. Phasellus faucibus molestie nisl. Fusce nibh.

Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. In rutrum. Etiam bibendum elit eget erat. Aliquam in lorem sit amet leo accumsan lacinia. Phasellus rhoncus. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Aenean id metus id velit ullamcorper pulvinar. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nullam at arcu a est sollicitudin euismod. Phasellus et lorem id felis nonummy placerat. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In convallis. Suspendisse sagittis ultrices augue. Praesent id justo in neque elementum ultrices. Aliquam erat volutpat.</Text>

    )
}